name: Deploy to heroku

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          usedocker: true
          docker_heroku_process_type: web
        env:
          HD_SOLARMANAGER_APIUSER: ${{ secrets.SOLARMANAGER_APIUSER }}
          HD_SOLARMANAGER_APIPASSWORD: ${{ secrets.SOLARMANAGER_APIPASSWORD }}
